# Generated by Django 2.2.5 on 2019-10-09 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year',
            new_name='StudyYear',
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignment.StudyYear'),
        ),
    ]
