# Generated by Django 2.2.5 on 2019-10-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20191013_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
