# Generated by Django 2.2.5 on 2019-10-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20191009_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem',
            field=models.CharField(help_text='Enter in this format First  , Second , etc.', max_length=50),
        ),
    ]
