# Generated by Django 2.2.5 on 2019-10-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20191009_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='sem',
            field=models.IntegerField(),
        ),
    ]
