# Generated by Django 2.2.5 on 2019-10-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20191009_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
