# Generated by Django 2.2.5 on 2020-03-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20191022_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modelAnswer',
            field=models.TextField(blank=True),
        ),
    ]
