# Generated by Django 2.2.5 on 2020-03-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_question_modelanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='similarity',
            field=models.FloatField(null=True),
        ),
    ]
